TRANSFLAGS = -aggressive-conditions -lift # -split-if
RECOMPILEFLAGS = -u -show-compiles
SCHEDFLAGS = -show-schedule -sched-dot # -show-rule-rel dMemInit_request_put doExecute
#	-show-elab-progress
DEBUGFLAGS = -check-assert \
	-continue-after-errors \
	-keep-fires \
	-keep-inlined-boundaries \
	-show-method-bvi \
	-show-method-conf \
	-show-module-use \
	-show-range-conflict \
	-show-stats \
	-warn-action-shadowing \
	-warn-method-urgency \
	-promote-warnings ALL \
	-demote-errors S0015:G0020:G0023:S0073
VERILOGFLAGS = -verilog -remove-dollar # -use-dpi -verilog-filter cmd
BLUESIMFLAGS = -parallel-sim-link 16 # -systemc
BUILDDIR = build
OUTDIR = -bdir $(BUILDDIR) -info-dir $(BUILDDIR) -simdir $(BUILDDIR) -vdir $(BUILDDIR)
WORKDIR = -fdir $(abspath .)
BSVSRCDIR = -p +:$(abspath ../src) \
			-p +:$(abspath ../test)


BLUE_RDMA_DMA_IP_TYPE ?= XILINX_BLUE_DMAC
BLUE_RDMA_ETH_IP_TYPE ?= XILINX_CMAC

ifeq ($(BLUE_RDMA_DMA_IP_TYPE), XILINX_XDMA)
	BSVSRCDIR += -p +:$(abspath ../src/vendor/xilinx/xdma)
else ifeq ($(BLUE_RDMA_DMA_IP_TYPE), XILINX_BLUE_DMAC)
	BSVSRCDIR += -p +:$(abspath ../src/vendor/xilinx/blue-dmac)
	BSVSRCDIR += -p +:$(abspath ../src/vendor/xilinx/blue-dmac/blue-dmac/src)
	BSVSRCDIR += -p +:$(abspath ../src/vendor/xilinx/blue-dmac/blue-dmac/lib/blue_wrapper/src)
endif

ifeq ($(BLUE_RDMA_ETH_IP_TYPE), XILINX_CMAC)
	BSVSRCDIR += -p +:$(abspath ../src/vendor/xilinx/cmac)
endif

MISCFLAGS += -D BLUE_RDMA_DMA_IP_TYPE_$(BLUE_RDMA_DMA_IP_TYPE)
MISCFLAGS += -D BLUE_RDMA_ETH_IP_TYPE_$(BLUE_RDMA_ETH_IP_TYPE)

BSV_C_EXT_FILES += \
	$(abspath ../src)/MockHost.c



BLUERDMA_BUILD_TARGET ?= XILINX_100G

ifeq ($(BLUERDMA_BUILD_TARGET), XILINX_100G)
	BLUERDMA_DATA_BUS_WIDTH = 512
endif

DIRFLAGS = $(BSVSRCDIR) $(OUTDIR) $(WORKDIR)
MISCFLAGS += -print-flags -show-timestamps -show-version -steps 6000000
RUNTIMEFLAGS = +RTS -K4095M -RTS
