
CSR_ADDR_SEND_QUEUE_ADDR_LOW = 0x00 << 5
CSR_ADDR_SEND_QUEUE_ADDR_HIGH = 0x01 << 5
CSR_ADDR_SEND_QUEUE_HEAD = 0x02 << 5
CSR_ADDR_SEND_QUEUE_TAIL = 0x03 << 5

CSR_ADDR_META_REPORT_QUEUE_ADDR_LOW = 0x04 << 5
CSR_ADDR_META_REPORT_QUEUE_ADDR_HIGH = 0x05 << 5
CSR_ADDR_META_REPORT_QUEUE_HEAD = 0x06 << 5
CSR_ADDR_META_REPORT_QUEUE_TAIL = 0x07 << 5

CSR_ADDR_CMD_REQ_QUEUE_ADDR_LOW = 0x40 << 5
CSR_ADDR_CMD_REQ_QUEUE_ADDR_HIGH = 0x41 << 5
CSR_ADDR_CMD_REQ_QUEUE_HEAD = 0x42 << 5
CSR_ADDR_CMD_REQ_QUEUE_TAIL = 0x43 << 5

CSR_ADDR_CMD_RESP_QUEUE_ADDR_LOW = 0x44 << 5
CSR_ADDR_CMD_RESP_QUEUE_ADDR_HIGH = 0x45 << 5
CSR_ADDR_CMD_RESP_QUEUE_HEAD = 0x46 << 5
CSR_ADDR_CMD_RESP_QUEUE_TAIL = 0x47 << 5


# CSR_ADDR_HARDWARE_CONST_HW_VERSION = generate_csr_addr(
#     CsrGroupIndex.HardwareConsts, CsrGroupOffsetForHardwareConst.HwVersion)
# CSR_ADDR_HARDWARE_GLOBAL_CONTROL_SOFT_RESET = generate_csr_addr(
#     CsrGroupIndex.HardwareGlobalControl, CsrGroupOffsetForHardwareGlobalControl.SoftReset)
